name: Setup Bowtie
run-name: ${{ github.actor }} is learning to use Bowtie

on: [push]

jobs:
  sets-up-bowtie:
    runs-on: ubuntu-latest

    steps:
      - name: Install Bowtie
        uses: bowtie-json-schema/bowtie@v2023.05.12

      - name: Run Bowtie
        run: bowtie --version

      - name: Test step
        run: pwd

      - name: Validate Schema
        run: bowtie validate bowtie-actions-example/schema.json bowtie-actions-example/instance.json