name: Setup Bowtie
run-name: ${{ github.actor }} is learning to use Bowtie

on: [push]

jobs:
  sets-up-bowtie:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Bowtie
        uses: bowtie-json-schema/bowtie@v2023.05.12

      - name: Run Bowtie
        run: bowtie --version

      - name: Validate Schema
        run: bowtie validate -i lua-jsonschema --dialect 7 -i python-jsonschema --dialect 6 schema.json instance.json